---
title: "TEAPO_All Code_Anchit Goyal"
output: html_notebook
---



```{r}
library(tidyverse)
library(haven)
library(Matrix)
library(lmtest)
library(sandwich)
library(matrixcalc)
library(estimatr)
library(tseries)
library(urca)
library(caret)
library(leaps)
library(glmnet)
library(ggthemes)
library(doParallel)
library(MLeval)
library(VGAM)
library(caTools)
library(ISLR)
library(pROC)
library(klaR) 
library(e1071)
library(ROCR)
library(boot)
library(MASS)
library(naivebayes)
library(dplyr)
library(ggplot2)
library(psych)
library(stargazer)
library(plm)
library(data.table)
library(tidyr)
library(systemfit)
library(skedastic)
library(car)
library(GGally)
library(panelvar)
library(quantmod)
library(xts)
library(MTS)
library(fUnitRoots) 
library(timeSeries)
library(fGarch)
library(dynlm)
library(fUnitRoots)
library(tseries)
library(urca)
library(quantmod)
library(timeSeries)
library(pglm)
```

```{r}
df <- read.csv("/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/50 US Governors_Edited.csv")
df <- df[, -c(19)]

long_panel(df, prefix = "X20", begin = 05, end = 21, label_location = "end")

reshape(as.data.frame(df), sep = "X20", times = c(05, 06, 07, 08, 09, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21), direction = "long", varying = c("X2005", "X2006", "X2007", "X2008", "X2009", "X2010", "X2011", "X2012", "X2013", "X2014", "X2015", "X2016", "X2017", "X2018", "X2019", "X2020", "X2021" ))
```

```{r}
##For Political Data Set ## 0 is Republican 1 is democrat
long_gos <- melt(setDT(df), id.vars = c("State"), varaible.name ="year")

df_GOS<- df %>% gather(year, value, -c(State))

write.csv(df_GOS,"/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/GOS_data.csv", row.names = FALSE)
```

```{r}
##For GDP Data Set - RGDP in Levels
raw_df<- read.csv("/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Real GDP_in Quarters.csv")

raw_df <- raw_df[, -c(2)]

df_gdp <- raw_df %>% gather(year, value, -c(Time))

write.csv(df_gdp,"/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/GDP_data.csv", row.names = FALSE)
```

```{r}
##For % Change in Real GDP Data 
pcrgdp_df<- read.csv("/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Real GDP/Q2Qdifference_RGDP_transpose.csv")

pcrgdp_df <- pcrgdp_df[, -c(2)]

df_percentgdp <- pcrgdp_df %>% gather(year, value, -c(GeoName))

write.csv(df_percentgdp,"/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/percentchange_realgdp.csv", row.names = FALSE)
```

```{r}
## For GDP Growth Rate

raw_gdpgrowth_df <- read.csv("/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Real GDP/GDP True Growth Rate in percentages.csv")

raw_gdpgrowth_df <- raw_gdpgrowth_df [, -c(2)]

df_gdpgrowth <- raw_gdpgrowth_df %>% gather (year, value, -c(Time))

write.csv(df_gdpgrowth,"/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Real GDP/GDP Growth Rate Final.csv", row.names = FALSE)
```


```{r}
##For Unemployment Data Set 

raw_df_ur <- read.csv("/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Unemployment Rate_States.csv")

df_ur <- raw_df_ur %>% gather(year, value, -c(Area))

write.csv(df_ur,"/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Unemployment Rate_FinalData.csv", row.names = FALSE)
```

```{r}
##For Income Data Set

##Not necessary as Data is already in Panel Format
raw_income_df <- read.csv("/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Income Data/Income Data Sorted.csv")
```



```{r}
fdf <- read.csv("/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Final Data_1.csv")

#write.csv(fdf,"/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Final Data_2.csv", row.names = FALSE)


fdf$lrgdp<- log(fdf$GDP) 

fdf$lii <- log(fdf$ineq)

#Analysis begins here.

fdf_2<- read.csv("C:\Users\anchi\OneDrive\Desktop\NYU\Sem II\ATSPD\Final Data_2.csv")

fdf_2$LUR <- log(fdf_2$UR)
fdf_2$l_inc_diff <- log(fdf_2$inc_diff)

pdf <- pdata.frame(fdf_2, c("State", "Year"))


gosols <- systemfit(pcrgdp~ Ugrowth, method="OLS", data =pdf)
summary(gosols)

gosols1 <- systemfit(GOS ~ pcrgdp + UR, method="SUR", data =pdf)

fe <- plm (lrgdp ~ UR + GOS + lii, method="within", data =pdf)
summary(fe)

fe1 <- plm(GOS ~ UR + lrgdp + lii, method ="within", data =pdf)
summary(fe1)

fe2 <- plm(GOS ~ UR + pcrgdp, method ="between", data =pdf)
summary(fe2)

re2 <- plm(GOS ~ UR + pcrgdp, data = pdf, model = "random", random.method = "walhus")
summary(re2)

phtest(re2, fe2)

##Check for correlations
cor.test(pdf$UR,pdf$pcrgdp)
cor.test(pdf$lii, pdf$lrgdp)
cor.test(pdf$GOS, pdf$UR)
cor.test(pdf$GOS, pdf$lii)
cor.test(pdf$GOS, pdf$lrgdp) ##Not correlated
cor.test(pdf$GOS, pdf$pcrgdp) ##Not correlated
cor.test(pdf$pcrgdp, pdf$lrgdp) ## Not Correlated
cor.test(pdf$ineq, pdf$GOS)
cor.test(pdf$ineq, pdf$lrgdp) ##Not Correlated


cor.test(pdf$GDP_Growth, pdf$perchg_inc_ineq) ##Not Correlated at 1%
cor.test(pdf$GDP_Growth, pdf$GOS) ##Not correlated at 10%
cor.test(pdf$GDP_Growth, pdf$Ugrowth) ##Not Correlated
cor.test(pdf$Ugrowth, pdf$perchg_inc_ineq) ##Not Correlated at 5%

###Fixed - Within
few_reg_ur <- plm(Ugrowth ~ GOS + GDP_Growth, data = pdf, model ="within")
summary(few_reg_ur)

few_reg_ur <- plm(Ugrowth ~ GOS + GDP_Growth + Non.Crisis.Year, data = pdf, model ="within")
summary(few_reg_ur)

few_reg_income <- plm(ineq ~ GOS + Ugrowth, data = pdf, model ="within")
summary(few_reg_income)

few_reg_income <- plm(ineq ~ GOS, data = pdf, model ="within")
summary(few_reg_income)


few_reg <- plm(Ugrowth ~ ineq + GDP_Growth, data = pdf, model ="within")
summary(few_reg)

few_reg_2 <- plm(ineq ~ Ugrowth + GDP_Growth, data = pdf, model ="within")
summary(few_reg_2)

few_reg_3 <- plm(GDP_Growth ~ Ugrowth + ineq, data = pdf, model ="within")
summary(few_reg_3)

few_reg_ineq <- plm(perchg_inc_ineq ~ GOS + Ugrowth, data = pdf, model ="within")
summary(few_reg_ineq)

few_reg_ineq_r <- plm(perchg_inc_ineq ~ GOS + Ugrowth + Non.Crisis.Year, data = pdf, model ="within")
summary(few_reg_ineq_r)

reg<- lm(ineq ~ Ugrowth, data = pdf)

few_reg_gdp <- plm(GDP_Growth ~ Ugrowth + GOS, data = pdf, model ="within")
summary(few_reg_gdp)


few_reg_gdp <- plm(GDP_Growth ~ GOS + Non.Crisis.Year + Ugrowth, data = pdf, model ="within")
summary(few_reg_gdp)

###Random
re_reg_ur <- plm(Ugrowth ~ GOS + GDP_Growth, data = pdf, model = "random", random.method = "walhus")
summary(re_reg_ur)

re_reg_income <-plm(ineq ~ GOS + Ugrowth, data = pdf, model = "random", random.method = "walhus")
summary(re_reg_income)

re_reg_gdp <-plm(GDP_Growth ~ Ugrowth + GOS, data = pdf, model = "random", random.method = "walhus")
summary(re_reg_gdp)

plot(reg)

plot(re_reg_gdp$residuals)

#Hausman for UR
phtest(few_reg_ur, re_reg_ur) #Use Fixed Effects
phtest(few_reg_income, re_reg_income) #Use Fixed Effects
phtest(few_reg_gdp, re_reg_gdp) #Can use Random Effects

jotest=ca.jo(data.frame(pdf$perchg_inc_ineq, pdf$GDP_Growth), type="trace", K=2, ecdet="none", spec="longrun")
summary(jotest)

adfTest(fdf_2$LUR,type="nc") ##Stationary at 10%
adfTest(fdf_2$inc_diff, type="nc")
adfTest(fdf_2$l_inc_diff, type = "nc")
adfTest(fdf_2$ineq, type="nc")
adfTest(fdf_2$Ugrowth, type="c")
adfTest(fdf_2$Ugrowth, type="nc")
adfTest(pdf$perchg_inc_ineq, type ="c") #Stationary
adfTest(re_reg_gdp$residuals, type = "nc") ##Residuals are stationary
adfTest(pdf$Ugrowth,lags = 11, type = "ct")
adfTest(pdf$Ugrowth, type = "c")
adfTest(pdf$Ugrowth, type = "nc")

adfTest(pdf$GDP_Growth, type ="ct")

plot(pdf$perchg_inc_ineq)
adfTest(pdf$perchg_inc_ineq, type = "ct")

adfTest(pdf$UR,lags = 11, type = "ct")
adfTest(pdf$UR, type = "c")
adfTest(pdf$UR, type = "nc")
adfTest(pdf$Non.Crisis.Year*pdf$Ugrowth)

#fdf_3 <- data.frame(split(pdf$Ugrowth, pdf$State))
#pdf_2 <- pdata.frame(fdf_3, c("State", "Year"))
#purtest(fdf_3, test = "ips", exo ="trend", lags ="AIC", pmax = "0")


unitrootTest(fdf_2$Ugrowth, lags= 20, type = "ct")
adf.test(pdf$Ugrowth)

adf = ur.df(y=fdf_2$Ugrowth, type ="trend", lags = 1, selectlags = "BIC")

summary(adf)
##Replace UTAH
##Use % difference
##


```
```{r}
fdf_2<- read.csv("/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Final Data_2.csv")

pdf <- pdata.frame(fdf_2, c("State", "Year"))
```



```{r}
#Modelling GDP

fe_w_gdp_1 <- plm(GDP_Growth ~ GOS , data = pdf, model ="within")
summary(fe_w_gdp_1)

fe_w_gdp_2 <- plm(GDP_Growth ~ GOS +Ugrowth , data = pdf, model ="within")
summary(fe_w_gdp_2)

fe_w_gdp_3 <- plm(GDP_Growth ~ GOS +Ugrowth +perchg_inc_ineq , data = pdf, model ="within")
summary(fe_w_gdp_3)

r_gdp_1 <- plm(GDP_Growth ~ GOS , data = pdf, model ="random")
summary(r_gdp_1)

r_gdp_2 <- plm(GDP_Growth ~ GOS +Ugrowth , data = pdf, model ="random")
summary(r_gdp_2)

r_gdp_3 <- plm(GDP_Growth ~ GOS +Ugrowth + perchg_inc_ineq , data = pdf, model ="random")
summary(r_gdp_3)

```



```{r}
#Modelling Unemployment

fe_w_u_1 <- plm(Ugrowth ~ GOS , data = pdf, model ="within")
summary(fe_w_u_1)

fe_w_u_2 <- plm(Ugrowth ~ GOS + perchg_inc_ineq , data = pdf, model ="within")
summary(fe_w_u_2)

fe_w_u_3 <- plm(Ugrowth ~ GOS + perchg_inc_ineq + GDP_Growth, data = pdf, model ="within")
summary(fe_w_u_3)


r_u_1 <- plm(Ugrowth ~ GOS , data = pdf, model ="random")
summary(r_u_1)

r_u_2 <- plm(Ugrowth ~ GOS + perchg_inc_ineq , data = pdf, model ="random")
summary(r_u_2)

r_u_3 <- plm(Ugrowth ~ GOS + perchg_inc_ineq + GDP_Growth, data = pdf, model ="random")
summary(r_u_3)
```



```{r}
#Modelling Inequality 

fe_w_ineq_1 <- plm(perchg_inc_ineq ~ GOS , data = pdf, model ="within")
summary(fe_w_ineq_1)

fe_w_ineq_2 <- plm(perchg_inc_ineq ~ GOS + GDP_Growth, data = pdf, model ="within")
summary(fe_w_ineq_2)

fe_w_ineq_3 <- plm(perchg_inc_ineq ~ GOS + GDP_Growth + Ugrowth, data = pdf, model ="within")
summary(fe_w_ineq_3)

fe_w_ineq_4 <- plm(perchg_inc_ineq ~ GOS + U_Growth , data = pdf, model ="within")
summary(fe_w_ineq_4)


re_ineq_1 <- plm(perchg_inc_ineq ~ GOS , data = pdf, model ="random")
summary(re_ineq_1)

re_ineq_2 <- plm(perchg_inc_ineq ~ GOS +GDP_Growth, data = pdf, model ="random")
summary(re_ineq_2)

re_ineq_3 <- plm(perchg_inc_ineq ~ GOS +GDP_Growth + Ugrowth, data = pdf, model ="random")
summary(re_ineq_3)

re_ineq_4 <- plm(perchg_inc_ineq ~ GOS + Ugrowth, data = pdf, model ="random")
summary(re_ineq_4)

```

```{r}
#hausman Test

#For GDP 

phtest(fe_w_gdp_1, r_gdp_1) #Do not reject null, use RE

phtest(fe_w_gdp_2, r_gdp_2)

phtest(fe_w_gdp_3, r_gdp_3)


#For unemployment

phtest(fe_w_u_1, r_u_1)

phtest(fe_w_u_2, r_u_2) ##Do not Reject Null , USE RE

phtest(fe_w_u_3, r_u_3)

#For Inequality

phtest(fe_w_ineq_1, re_ineq_1)  #Do not reject null, therefore use RE

phtest(fe_w_ineq_2, re_ineq_2)

phtest(fe_w_ineq_3, re_ineq_3)
```

```{r}
###Modelling Economic Theory Relationships
fe_1 <- plm(perchg_inc_ineq ~ Ugrowth , data = pdf, model ="within")
summary(fe_1)

fe_2 <- plm(GDP_Growth ~ Ugrowth , data = pdf, model ="within")
summary(fe_2)

fe_3 <- plm(Ugrowth ~ GDP_Growth , data = pdf, model ="within")
summary(fe_3)

fe_4 <- plm(Ugrowth ~ perchg_inc_ineq, data = pdf, model ="within")
summary(fe_4)

fe_5 <- plm(GDP_Growth ~ perchg_inc_ineq, data = pdf, model ="within") ###Interesting Result, can add in the paper
summary(fe_5)

fe_6 <- plm(perchg_inc_ineq ~ GDP_Growth, data = pdf, model ="within")
summary(fe_6)

fe_7 <- plm(GOS ~ perchg_inc_ineq + GDP_Growth + Ugrowth, data = pdf, model ="within",family = "binomial")
summary(fe_7)


fe_8 <- pglm(GOS ~ GDP_Growth + perchg_inc_ineq, data = pdf, model = "within", effect ="individual", family = "binomial", start = "start")
summary(fe_8)
```

##################
```{r}
cor.test(pdf$GDP_Growth, re_ineq_2$residuals)

cor.test(pdf$Ugrowth, pdf$GOS)

phtest(fe_w_ineq_1, re_ineq_1)
phtest(fe_w_ineq_3, re_ineq_2)
```


```{r}

sampledf <- read.csv("/Users/anchitgoyal/Desktop/NYU/Sem_2/Applied Time Series and Panel Data/Data Points/Sample Final Data_2.csv")
pdf_2 <- pdata.frame(sampledf, c("State", "Year"))

reg<- lm(ineq ~ Ugrowth, data = pdf_2)

plot(reg)

few_reg_income <- plm(ineq ~ Ugrowth, data = pdf_2, model ="between")
summary(few_reg_income)
plot(few_reg_income)
```
```{r}
#first difference transformation
pvar_fd <- pvargmm(
  dependent_vars= c(, "ineq", ) ,
  lags=1 ,
  exog_vars =c("GOS"),
  transformation = "fd",
  data = pdf,
  panel_identifier = c("State", "Year"),
  steps = c("twostep"),
  system_instruments = FALSE,
  system_constant = TRUE,
  pca_instruments = FALSE,
  pca_eigenvalue = 1,
  min_instr_dependent_vars = 2L,
  min_instr_predet_vars = 1L,
  collapse = FALSE,
  tol = 1e-09,
  progressbar = TRUE
)

summary(pvar_fd)

#fod transformation

pvar_fod <- pvargmm(
  dependent_vars= c("Ugrowth", "per", "GDP_Growth", "GOS") ,
  lags=1,
  exog_vars =c("GOS"),
  transformation = "fod",
  data = pdf,
  panel_identifier = c("State", "Year"),
  steps = c("twostep"),
  system_instruments = FALSE,
  system_constant = TRUE,
  pca_instruments = FALSE,
  pca_eigenvalue = 1,
  min_instr_dependent_vars = 2L,
  min_instr_predet_vars = 1L,
  collapse = FALSE,
  tol = 1e-09,
  progressbar = TRUE
)

summary(pvar_fod)

```
```{r}
plot(pdf$Ugrowth)
```

